#!/usr/bin/env python3
"""Generate fixtures/success/ and fixtures/baseline/ from the F.1 illustrative examples.

The Canonical Record spans are located in the pretty-printed F.1 example files
with the lexeme-preserving scanner and converted to canonical bytes by removing
whitespace outside strings (lexemes are copied verbatim, never re-serialized),
then terminated with one LF. Each file gets a <name>.json.sha256 sidecar.

Usage: python tools/generate_success_fixtures.py [--out-dir fixtures]
"""

import argparse
import sys
from pathlib import Path

import _paths  # noqa: F401
from pi3xi_audit.canonical import check_format, minify, scan, sha256_hex

# (output name, F.1 example file, path to the record inside the example envelope)
SOURCES = [
    ("success/verify-success.json", "examples/verify-success.json", ("record",)),
    ("success/verify-fail.json", "examples/verify-fail.json", ("record",)),
    ("success/replay-0002.json", "examples/replay.json", ("records", 1)),
    ("success/replay-0003.json", "examples/replay.json", ("records", 2)),
    ("baseline/baseline.json", "examples/replay.json", ("records", 2)),
]


def locate(node, path):
    for step in path:
        node = dict(node.members)[step] if isinstance(step, str) else node.members[step]
    return node


def write_pair(path: Path, data: bytes):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    path.with_name(path.name + ".sha256").write_bytes((sha256_hex(data) + "\n").encode("ascii"))


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default=str(_paths.PACKAGE_ROOT / "fixtures"))
    args = ap.parse_args(argv)
    out = Path(args.out_dir)
    for name, src, path in SOURCES:
        text = (_paths.REPO_ROOT / src).read_bytes().decode("utf-8")
        _, doc, _ = scan(text)
        data = (minify(locate(doc, path).raw) + "\n").encode("utf-8")
        check_format(data)  # generated bytes must be canonical
        write_pair(out / name, data)
        print(f"{sha256_hex(data)}  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
